[project]
authors = ["Gregor Niehl <gregorniehl@web.de>"]
channels = ["robostack-staging", "conda-forge"]
name = "my_ros2_project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "colcon build --symlink-install"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
# ros-humble-turtlesim = ">=1.4.2,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ruff = ">=0.11.2,<0.12"
jedi-language-server = ">=0.44.0,<0.45"
python-lsp-server-base = ">=1.12.2,<2"
python-lsp-server = ">=1.12.2,<2"

[activation]
scripts = ["install/setup.sh"]

[pypi-dependencies]
luma-core = ">=2.4.2, <3"
luma-oled = ">=3.14.0, <4"
rpi-gpio = ">=0.7.1, <0.8"
